name: Lint Check (Angular)

# プッシュされるたびに実行。除外条件なし。
on: push

# 環境変数設定
env:
  REGISTRY: ghcr.io
  IMAGE_PATH: ghcr.io/${{ github.repository }}:main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # ソースコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v6

      # GHCRへのログイン
      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # mainタグのイメージを取得。
      - name: Pull Docker image
        run: docker pull ${{ env.IMAGE_PATH }}

      # Lintコマンドの実行。
      - name: Run Lint
        # ホストのコードをコンテナ内の作業ディレクトリ(/app)にマウントして実行
        run: docker run --rm --mount type=bind,source=${{ github.workspace }},target=/app ${{ env.IMAGE_PATH }} npm run lint
