name: Unit Test (Angular)

on:
  # プッシュされるたびに実行。
  # mainブランチかつDocker関連ファイルに変更がある場合は実行をキャンセルし、Dockerイメージビルド完了後に再度実行する。
  # on pushで複雑な条件を記述できないため。
  push:
  # Dockerイメージのビルドが完了してから実行
  workflow_run:
    workflows: ['Publish Docker Image (develop)']
    types: [completed]

# 環境変数設定
env:
  REGISTRY: ghcr.io
  IMAGE_PATH: ghcr.io/${{ github.repository }}:main

jobs:
  # 事前条件判定 (workflow)
  precond_workflow:
    if: ${{ github.event_name == 'workflow_run' }}
    runs-on: ubuntu-latest
    steps:
      # ワークフローが成功でなければ終了。
      - name: Check if the trigger workflow is successful
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
            exit 1
          fi

  # 事前条件判定 (push && main branch)
  precond_push:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      # mainブランチの場合、変更ファイルを調べるためにリポジトリをチェックアウト。
      # メタデータだけでいいのでスパースチェックアウト。
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          sparse-checkout: .

      - name: Check if Docker related files changed
        run: |
          # 変更されたファイルの一覧を取得
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files:"
          echo "$CHANGED_FILES"

          # Docker関連ファイルが含まれているかチェック
          if echo "$CHANGED_FILES" | grep -E 'Dockerfile|\.dockerignore|package-lock\.json'; then
            echo "Docker related files changed. Cancelling this workflow to wait for Docker build."
            exit 1
          fi

  # テスト実行
  test:
    needs:
      - precond_workflow
      - precond_push
    # 依存ジョブのいずれかがスキップされても、失敗やキャンセルがなければ実行する
    if: >-
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # ソースコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # GHCRへのログイン
      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # mainタグのイメージを取得。
      - name: Pull Docker image
        run: docker pull ${{ env.IMAGE_PATH }}

      # Lintコマンドの実行。
      - name: Run Unit Test
        # ホストのコードをコンテナ内の作業ディレクトリ(/app)にマウントして実行
        # チェックアウトしたソースツリーでDockerイメージのnode_modulesが上書きされてしまうのを防止するために
        # /app/node_modulesに対して匿名ボリュームをマウント。
        run: |
          docker run --rm \
            --mount type=bind,source=${{ github.workspace }},target=/app \
            --mount type=volume,target=/app/node_modules \
            ${{ env.IMAGE_PATH }} \
            npm run test -- --watch=false --reporters=default --reporters=junit --output-file=test-results.xml

      # テストレポートの表示
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: always() # テストが失敗しても必ず実行してレポートを出す
        with:
          name: Vitest Unit Test Results
          path: test-results.xml
          reporter: java-junit

      # テストレポートの保存
      - name: Archive Test Report
        uses: actions/upload-artifact@v4
        if: always() # テストが失敗しても必ず実行してレポートを保存する
        with:
          name: vitest-junit-results
          path: test-results.xml
          retention-days: 7
